
version: 2

models:
    

    - name: topsal
      description: "A starter dbt model"
      columns:
          - name: RANK_
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
            
